-- 1. 참여자 정보를 저장할 테이블 생성
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. RLS(Row Level Security) 설정 활성화
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;

-- 3. 누구나 조회 및 삽입할 수 있는 간단한 정책 추가 (익명 사용자용)
CREATE POLICY "Allow public read access" ON public.members 
    FOR SELECT USING (true);

CREATE POLICY "Allow public insert access" ON public.members 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public delete access" ON public.members 
    FOR DELETE USING (true);
